feat:add new nrt on executions part
Decathlon/ara pull request #300
Opened 2020-08-26 11:21 UTC by z25clave

## Type of modification

* [ ] Breaking change
* [ ] New Feature
* [ ] Bug Fix
* [ v ] Chore (refactor, documentation, tests... all the changes with no impact on ARA functionalities.) 

## Changes description

**Add some quick description about what your PullRequest change in
ARA's feature/behavior**

## Technical description

**Add a quick description about what your PullRequest change in 
ARA's code. (example: add a processor check in...)**

## PR CheckList

Please make sure your PullRequest respect all those items :

* [ v ] Your PR's title has the prefix : `feat:`, `fix:` or `chore:`
* [ ] Unless your PR is related to a Hotfix (and approved by a ARA maintener), the targeted branch for it is the branch `version/X.Y.Z` and **not** `master`
* [ ] You have asked a review from one of the ARA maintainer in your PR.
* [ ] If your PR is related to an issue, add the issue's number in it.
* [ ] All the code you added is documented.
* [ ] All the code you added is tested and the  tests are in success.
* [ v ] You already signed the [Contributor License Agreement](https://github.com/Decathlon/ara/blob/master/contributor-licence-agreement.adoc) and give us the document

2020-08-26 11:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Decathlon/ara?pullRequest=300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Decathlon/ara?pullRequest=300) before we can accept your contribution.<br/><hr/>**Caroline Lavergne** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Decathlon/ara?pullRequest=300) it.</sub>

2020-08-26 11:43 UTC, BenjaminDupont approved these changes

2020-08-28 08:57 UTC, omar-chahbouni-decathlon requested changes
Please also update your commit message: feat -> test

2020-08-28 08:57 UTC, omar-chahbouni-decathlon commented on client/test/cypress/fixtures/executions_history.json
> +  "version": "benjAndCaro",
please change the version value

2020-08-28 08:57 UTC, omar-chahbouni-decathlon commented on client/test/cypress/fixtures/executions_history.json
> +          "vcsUrl": "https://github.com/decathlon/ara/tree/{{branch}}/server/src/main/resources/demo/collections/",
please make it more generic, like for example: https://vcs-url.com/company/tree/{{branch}}/collections

2020-08-28 08:57 UTC, omar-chahbouni-decathlon commented on client/test/cypress/fixtures/executions_history.json
> +          "vcsUrl": "https://github.com/decathlon/ara/tree/{{branch}}/generated-cucumber-report/src/main/resources/ara/demo/features/",
idem here

2020-08-28 09:00 UTC, omar-chahbouni-decathlon commented
please sign the licence/cla and fix the semantic pull request -> test: add new nrt on executions part

2020-08-31 08:10 UTC, omar-chahbouni-decathlon approved these changes

2020-08-31 08:10 UTC, merged