feat: display number of selected functionalities
Decathlon/ara pull request #340
Opened 2020-10-09 14:33 UTC by VviGit

Closes #336

## Type of modification

* [ ] Breaking change
* [x] New Feature
* [ ] Bug Fix
* [ ] Chore (refactor, documentation, tests... all the changes with no impact on ARA functionalities.) 

## Changes description

**On the Functionalities/cartography view, display the number of selected items**

## Technical description

**Add a new item in counts object, increment it when item is checked**

## PR CheckList

Please make sure your PullRequest respect all those items :

* [ ] Your PR's title has the prefix : `feat:`, `fix:` or `chore:`
* [ ] You have asked a review from one of the ARA maintainer in your PR.
* [ ] If your PR is related to an issue, add the issue's number in it.
* [ ] All the code you added is documented.
* [ ] All the code you added is tested and the  tests are in success.
* [ ] You already signed the [Contributor License Agreement](https://github.com/Decathlon/ara/blob/main/doc/contributing/contributor-licence-agreement.adoc) and give us the document

2020-10-09 14:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Decathlon/ara?pullRequest=340) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Decathlon/ara?pullRequest=340) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Decathlon/ara?pullRequest=340) it.</sub>

2020-10-09 15:12 UTC, omar-chahbouni-decathlon requested changes

2020-10-09 15:12 UTC, omar-chahbouni-decathlon commented on client/src/views/functionality-cartography.vue
>              child.isSelected = node.isSelected
wouldn't be simpler to write something like below?

```
if (child.row.type === 'FUNCTIONALITY' && node.isSelected !== child.isSelected) {
  const increment = node.isSelected ? 1 : - 1
  this.counts.selected += 1
}
```

I didn't understand the intent of your code right away. Feel free to tell me what you think ;)

2020-10-12 08:16 UTC, VviGit commented on client/src/views/functionality-cartography.vue
> -            <span v-else>Showing <strong>{{counts.matching}}</strong> filtered functionalit{{counts.matching == 1 ? 'y' : 'ies'}} out of the <strong>{{counts.total}}</strong> functionalit{{counts.tot
Seems better english to me :)

2020-10-12 08:45 UTC, omar-chahbouni-decathlon requested changes
This seems ok. 
Can you just keep the first commit ?

2020-10-12 09:33 UTC, omar-chahbouni-decathlon approved these changes

2020-10-12 09:37 UTC, merged